services:
  # Web service for the Flask app
  - type: web
    name: cricket-image-chatbot
    env: python
    region: singapore
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --timeout 120 --log-level debug
    envVars:
      # Aiven PostgreSQL database credentials
      # These should be updated with your actual Aiven PostgreSQL credentials
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: YOUR_AIVEN_PASSWORD_HERE
      - key: DB_HOST
        value: pg-3c5659d2-saneeipk-09e5.k.aivencloud.com
      - key: DB_PORT
        value: '20432'
      # Groq API key for LLM service
      - key: GROQ_API_KEY
        sync: false
      # Ensure Python output is not buffered
      - key: PYTHONUNBUFFERED
        value: 'true'
      # Flask secret key
      - key: SECRET_KEY
        generateValue: true
      # Flask port
      - key: PORT
        value: '10000'
    healthCheckPath: /login
    # Increase the health check timeout
    healthCheckTimeout: 180
